-- MySQL Script generated by MySQL Workbench
-- Wed 06 Nov 2019 03:45:10 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `Codigo` CHAR(5) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Usuario` TINYINT NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `Cui` INT NOT NULL,
  `CodigoArea` CHAR(5) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Igss` FLOAT NOT NULL,
  `Irtra` FLOAT NOT NULL,
  PRIMARY KEY (`Cui`),
  INDEX `fk_Area_Empleado_idx` (`CodigoArea` ASC),
  CONSTRAINT `fk_Area_Empleado`
    FOREIGN KEY (`CodigoArea`)
    REFERENCES `mydb`.`Area` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Cui` INT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserName`),
  INDEX `fk_Cui_Usuario_idx` (`Cui` ASC),
  CONSTRAINT `fk_Cui_Usuario`
    FOREIGN KEY (`Cui`)
    REFERENCES `mydb`.`Empleado` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PeriodoLaboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PeriodoLaboral` (
  `Codigo` VARCHAR(5) NOT NULL,
  `Cui` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Empleado_PeriodoLaboral_idx` (`Cui` ASC),
  CONSTRAINT `fk_Empleado_PeriodoLaboral`
    FOREIGN KEY (`Cui`)
    REFERENCES `mydb`.`Empleado` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especialista` (
  `Cui` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`Cui`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vacacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vacacion` (
  `Codigo` INT NOT NULL,
  `Cui` VARCHAR(45) NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`),
  CONSTRAINT `fk_Empleado_Vacacion`
    FOREIGN KEY (`Codigo`)
    REFERENCES `mydb`.`Empleado` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoMedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoMedicamento` (
  `Codigo` CHAR(5) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `CantidadMinima` INT NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicamento` (
  `Codigo` CHAR(5) NOT NULL,
  `CodigoTipo` CHAR(5) NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Tipo_Medicamento_idx` (`CodigoTipo` ASC),
  CONSTRAINT `fk_Tipo_Medicamento`
    FOREIGN KEY (`CodigoTipo`)
    REFERENCES `mydb`.`TipoMedicamento` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habitacion` (
  `Codigo` CHAR(5) NOT NULL,
  `Estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mantenimiento` (
  `CodigoHabitacion` CHAR(5) NOT NULL,
  `Costo` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`CodigoHabitacion`, `Fecha`),
  CONSTRAINT `fk_Codigo_Habitacion`
    FOREIGN KEY (`CodigoHabitacion`)
    REFERENCES `mydb`.`Habitacion` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `CodigoMedicamento` CHAR(5) NOT NULL,
  `Costo` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`CodigoMedicamento`),
  CONSTRAINT `fk_Codigo_Compra`
    FOREIGN KEY (`CodigoMedicamento`)
    REFERENCES `mydb`.`Medicamento` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `CodigoMedicamento` CHAR(5) NOT NULL,
  `CuiVendedor` INT NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodigoMedicamento`, `CuiVendedor`),
  INDEX `fk_Cui_Venta_idx` (`CuiVendedor` ASC),
  CONSTRAINT `fk_Cui_Venta`
    FOREIGN KEY (`CuiVendedor`)
    REFERENCES `mydb`.`Empleado` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_Venta`
    FOREIGN KEY (`CodigoMedicamento`)
    REFERENCES `mydb`.`Medicamento` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `Codigo` CHAR(5) NOT NULL,
  `Nit` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Internado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Internado` (
  `Codigo` CHAR(5) NOT NULL,
  `CodigoPaciente` CHAR(5) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `CodigoHabitacion` CHAR(5) NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFinal` DATE NULL,
  `Pagado` TINYINT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Habitacion_Internado_idx` (`CodigoHabitacion` ASC),
  CONSTRAINT `fk_Habitacion_Internado`
    FOREIGN KEY (`CodigoHabitacion`)
    REFERENCES `mydb`.`Habitacion` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Internado`
    FOREIGN KEY (`CodigoPaciente`)
    REFERENCES `mydb`.`Paciente` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `Codigo` CHAR(5) NOT NULL,
  `CodigoPaciente` CHAR(5) NOT NULL,
  `CuiMedico` INT NOT NULL,
  `Pago` FLOAT NOT NULL,
  `Costo` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Paciente_Consulta_idx` (`CodigoPaciente` ASC),
  INDEX `fk_Empleado_Consulta_idx` (`CuiMedico` ASC),
  CONSTRAINT `fk_Paciente_Consulta`
    FOREIGN KEY (`CodigoPaciente`)
    REFERENCES `mydb`.`Paciente` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Consulta`
    FOREIGN KEY (`CuiMedico`)
    REFERENCES `mydb`.`Empleado` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignacion` (
  `Cui` INT NOT NULL,
  `CodigoInternado` CHAR(5) NOT NULL,
  PRIMARY KEY (`Cui`),
  INDEX `fk_Internado_Asignacion_idx` (`CodigoInternado` ASC),
  CONSTRAINT `fk_Empleado_Asignado`
    FOREIGN KEY (`Cui`)
    REFERENCES `mydb`.`Empleado` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Internado_Asignacion`
    FOREIGN KEY (`CodigoInternado`)
    REFERENCES `mydb`.`Internado` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consumo` (
  `CodigoMedicamento` CHAR(5) NOT NULL,
  `CodigoInternado` CHAR(5) NOT NULL,
  PRIMARY KEY (`CodigoMedicamento`),
  INDEX `fk_Internado_Consumo_idx` (`CodigoInternado` ASC),
  CONSTRAINT `fk_Medicamento_Consumo`
    FOREIGN KEY (`CodigoMedicamento`)
    REFERENCES `mydb`.`Medicamento` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Internado_Consumo`
    FOREIGN KEY (`CodigoInternado`)
    REFERENCES `mydb`.`Internado` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoOperacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoOperacion` (
  `Codigo` CHAR(5) NOT NULL,
  `Nombre` VARCHAR(15) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `PagoEspecialista` FLOAT NOT NULL,
  `Costo` FLOAT NOT NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cirugia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cirugia` (
  `Codigo` CHAR(5) NOT NULL,
  `CodigoOperacion` CHAR(5) NOT NULL,
  `CodigoPaciente` CHAR(5) NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Operacion_Cirugia_idx` (`CodigoOperacion` ASC),
  INDEX `fk_Paciente_Cirugia_idx` (`CodigoPaciente` ASC),
  CONSTRAINT `fk_Operacion_Cirugia`
    FOREIGN KEY (`CodigoOperacion`)
    REFERENCES `mydb`.`TipoOperacion` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Cirugia`
    FOREIGN KEY (`CodigoPaciente`)
    REFERENCES `mydb`.`Paciente` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operar` (
  `CodigoCirugia` CHAR(5) NOT NULL,
  `CuiMedico` INT NOT NULL,
  PRIMARY KEY (`CodigoCirugia`),
  INDEX `fk_Empleado_Operar_idx` (`CuiMedico` ASC),
  CONSTRAINT `fk_Empleado_Operar`
    FOREIGN KEY (`CuiMedico`)
    REFERENCES `mydb`.`Empleado` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especialista_Operar`
    FOREIGN KEY (`CuiMedico`)
    REFERENCES `mydb`.`Especialista` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cirugia_Operar`
    FOREIGN KEY (`CodigoCirugia`)
    REFERENCES `mydb`.`Cirugia` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DatosAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DatosAdmin` (
  `DiasVacaciones` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `HabitacionPorDIa` FLOAT NULL,
  PRIMARY KEY (`DiasVacaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PagoEspecialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PagoEspecialista` (
  `Pago` INT NOT NULL,
  `CodigoOperacion` CHAR(5) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`CodigoOperacion`, `Fecha`),
  CONSTRAINT `fk_Operacion_PagoEspecialista`
    FOREIGN KEY (`CodigoOperacion`)
    REFERENCES `mydb`.`TipoOperacion` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sueldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Sueldo` (
  `Cui` INT NOT NULL,
  `Monto` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`Cui`,`Fecha`),
  CONSTRAINT `fk_Empleado_Sueldo`
    FOREIGN KEY (`Cui`)
    REFERENCES `hospital`.`Empleado` (`Cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
